### ISSUE TITLE
Refactor to better resemble ATS structure

### ISSUE THREAD

**Issue by djutras2** [opengeospatial/ets-geotiff11#18]
Reorganizing and restructuring code to better resemble the ATS may be another to-do. Depends on how strongly @dstenger and @cmheazel feel about adhering to the ATS and whether the current structure will cause confusion for future developers.

**Comment by cmheazel** [comment]
@djutras2 I would not consider this a high priority.  Quality of the ETS code is more important than ATS fidelity.

**Comment by cmheazel** [comment]
Close - should have been closed with the March 2 comment.
