### ISSUE TITLE
GeoTIFF Parser Analysis

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/ets-geotiff11#3]
Investigate limitations of existing GeoTIFF parsers used in the AGC tests.  Evaluate alternatives and recommend a way forward.

**Comment by djutras2** [comment]
A few comments:
- the previous/current implementation parsed tiffdump and listgeo output via streams. This doesn't work and a new method for parsing those contents is necessary (i.e. some wrapper class that allows for correct and easy reading of the output) if the tiffdump/listgeo approach is kept
- tiffdump limits listed values to only 24 items (will limit testing)
- listgeo provides a layer of abstraction that is good for readability, but complicates translation of tests from ATS to ETS
- Java options exists, e.g. [Apache Commons Imaging](http://commons.apache.org/proper/commons-imaging/index.html) or [GeoTiffReader](https://github.com/geotools/geotools/blob/master/modules/plugin/geotiff/src/main/java/org/geotools/gce/geotiff/GeoTiffReader.java)

**Comment by djutras2** [comment]
> tiffdump limits listed values to only 24 items (will limit testing)

On further inspection of tiffdump, the 24 value limit is a non-issue. Adding command option "-m" lets the user set a manual value. This wasn't in the documentation but can be seen in the source.

**Comment by djutras2** [comment]
I've come to bit of a crossroads on this where I really need quick access to EPSG codes. ListGeo doesn't seem to be up to date so I can either A) update listgeo's code tables, or B) implement a code look up table as an extension to the current TiffDump parser implementation. I've retrieved the tables from the EPSG website and am leaning towards the second option as being easier and quicker.

**Comment by cmheazel** [comment]
@djutras2 I vote for option B.  It would be best if the table is maintained as a separate resource.  That way it can be updated without having to modify the code.

**Comment by djutras2** [comment]
Can be closed
