### ISSUE TITLE
Random Access to Parsed GeoKeys

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/ets-geotiff11#5]
The current parser assumes that the ETS will access GeoKeys sequentially.  However, the ATS requires random access.  Many of the requirements are conditional, depending on the presence and values of other GeoKeys.  Therefore, the parser should return the parsed GeoKeys as an indexed data structure, allowing GeoKeys and their values to be accessed individually.

**Comment by djutras2** [comment]
This was essentially done via the TiffDump wrapper. Can be closed.
